version: '3'
services:
  lanyard:
    image: phineas/lanyard:latest
    ports:
      - "${PORT:-4001}:4001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - PORT=4001
    depends_on:
      - redis
  redis:
    image: redis:alpine